name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker builder
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/app-cityscape:latest

    - name: Login to Heroku Container Registry
      run: docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
      env:
        HEROKU_USERNAME: ${{ secrets.HEROKU_USERNAME }}
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    - name: Build and push to Heroku Container Registry
      run: |
        docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/app-cityscape:latest registry.heroku.com/app-cityscape-fd/web
        docker push registry.heroku.com/app-cityscape-fd/web

    - name: Deploy to Heroku
      run: heroku container:release web --app app-cityscape-fd
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
